config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "calculations#index"
  resources :calculations

  # Sidekiq
  require "sidekiq/web"
  require "sidekiq/cron/web"
  mount Sidekiq::Web => "/sidekiq"
end

app/models/calculation.rb
# frozen_string_literal: true

class Calculation < ApplicationRecord
  MAX_WEEKS = 250

  attribute :weeks_to_wait, :integer, default: 25
  belongs_to :user

  validates :base_amount, presence: true, numericality: true
  validates :base_currency, inclusion: { in: ExchangeRate::AVAILABLE_CURRENCIES }, presence: true
  validates :target_currency, inclusion: { in: ExchangeRate::AVAILABLE_CURRENCIES }, presence: true
  validate :base_and_target_currency_not_same

  validates :weeks_to_wait, numericality: { less_than_or_equal_to: Calculation::MAX_WEEKS, only_integer: true, greater_than_or_equal_to: 10 }
  validates :wait_until, inclusion: { in: (Date.today..Date.today + Calculation::MAX_WEEKS.weeks) }

  before_validation :set_wait_until

  private

    def set_wait_until
      self.wait_until = Date.current + weeks_to_wait.to_i.weeks if wait_until.blank?
    end

    def base_and_target_currency_not_same
      errors.add(:target_currency, "can't be the same as base currency") if base_currency == target_currency
    end
end

app/controllers/calculations_controller.rb
# frozen_string_literal: true

class CalculationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @calculations = current_user.calculations.order(created_at: :desc)
  end

  def new
    @calculation = Calculation.new
  end

  def edit
    @calculation = current_user.calculations.find(params[:id])
  end

  def update
    @calculation = current_user.calculations.find(params[:id])
    @calculation.assign_attributes(allowed_calculation_params)

    if @calculation.save
      flash[:notice] = "Calculation was succesfully updated"
      redirect_to @calculation
    else
      render :new
    end
  end

  def create
    @calculation = current_user.calculations.new(allowed_calculation_params)

    if @calculation.save
      flash[:notice] = "Calculation was succesfully created"
      redirect_to @calculation
    else
      render :new
    end
  end

  def destroy
    @calculation = current_user.calculations.find(params[:id])

    redirect_to calculations_path if @calculation.destroy
  end

  def show
    @calculation = current_user.calculations.find(params[:id])

    days_between_dates = (@calculation.created_at.to_date..@calculation.wait_until).count
    historical_data_db = build_rates_query(@calculation, days_between_dates)

    # Push the last rate for the current week to array
    @rate_data = [
      {
        week: historical_data_db.last[:week].to_i,
        year: historical_data_db.last[:year].to_i,
        exchange_rate: historical_data_db.last[:exchange_rate].to_f,
        target_amount: historical_data_db.last[:exchange_rate].to_f * @calculation.base_amount,
        forecast: false,
        profit: 0
      }
    ]

    # Forecast
    forecast_date = Date.current + 7.days

    forecast_data = HoltWinters.forecast(historical_data_db.collect { |rate| rate[:exchange_rate].to_f * @calculation.base_amount }, 0, 1, 0, 5, 4).reject { |item| item == 0 }
    forecast_data.each do |forecast_rate|
      @rate_data << {
        week: forecast_date.strftime("%W").to_i,
        year: forecast_date.strftime("%Y").to_i,
        exchange_rate: forecast_rate / @calculation.base_amount,
        target_amount: forecast_rate,
        forecast: true,
        profit: forecast_rate - @rate_data.first[:target_amount]
      }

      forecast_date += 7.days
    end

    # Rank calculation
    @rate_data = rank_rate_data(@rate_data)
    @top_profit_item = @rate_data.select { |rate_data_item| rate_data_item[:rank] == 1 }.first

    # Processing fetched data and storing it as instance variable for charting purposes
    @chart_data = get_chart_data(@calculation, historical_data_db, @rate_data)
  end

  def rank_rate_data(rate_data)
    rank = 1
    most_profitable = rate_data.dup.sort_by { |e| [e[:profit]] }.reverse.first(3)

    while rank <= 3
      rate_data.each do |value|
        next unless value[:week] == most_profitable[rank - 1][:week]
        value[:rank] = rank
        rank += 1
        break
      end
    end

    rate_data
  end

  def get_chart_data(calculation, historical_data, forecast_data)
    chart_data = {}

    %w(historical forecast).each do |key|
      weeks = []
      amount = []

      binding.local_variable_get("#{key}_data").each do |rate_row|
        weeks << "W#{rate_row[:week]} #{rate_row[:year]}"
        amount << (rate_row[:exchange_rate].to_f * calculation.base_amount).round(3)
      end

      chart_data[key.to_sym] = { weeks: weeks, amount: amount }
    end

    chart_data
  end

  private

    def allowed_calculation_params
      params.require(:calculation).permit(:base_currency, :target_currency, :base_amount, :wait_until, :weeks_to_wait)
    end

    def build_rates_query(calculation, days_between_dates)
      ExchangeRate.select("
date_part('year', created_at::date)::numeric as year,
date_part('week', created_at::date)::numeric as week,
COALESCE(avg((rate_data->>'#{calculation.target_currency}')::numeric),1)/COALESCE(avg((rate_data->>'#{calculation.base_currency}')::numeric),1) AS exchange_rate")
                       .where(created_at: (Date.current - days_between_dates.days)..calculation.created_at.to_date)
                       .group(:year, :week).sort_by { |e| [e.week, e.year] }
    end
end

app/views/calculations/_form.slim
= form_for @calculation do |f|

  - if @calculation.errors.any?
    .alert.alert-danger#errors
      ul
        - @calculation.errors.full_messages.each do |error_message|
          li = error_message

  .row


    .col
      .form-group
        = f.label :base_amount
        = f.text_field :base_amount, class: 'form-control'

    .col
      .form-group
        = f.label :base_currency
        = f.select :base_currency, options_for_select(ExchangeRate::AVAILABLE_CURRENCIES, @calculation.base_currency), {}, class: 'form-control'

  .row


    .col
      .form-group
        = f.label :target_currency
        = f.select :target_currency, options_for_select(ExchangeRate::AVAILABLE_CURRENCIES, @calculation.target_currency), {}, class: 'form-control'

    .col
      .form-group
        - if @calculation.id.present?

          = f.label :wait_until
          = f.text_field :wait_until, class: 'form-control', value: @calculation.wait_until.strftime("%d/%m/%Y")

        - else
          = f.label :weeks_to_wait, 'How many weeks to wait?'
          = f.text_field :weeks_to_wait, class: 'form-control'

  .row
    .col
      = f.submit class: 'form-control btn btn-dark'

app/views/calculations/edit.slim
h2 Editing Existing Calculation

hr

= render 'calculations/form'

app/views/calculations/index.slim
.row
  .col
    h2 Calculations

  .col-md-auto
    = link_to 'New Calculation', new_calculation_path, class: 'btn btn-primary'

.row
  .col
    hr

    - if @calculations.any?

      table.table.table-bordered
        thead
          th
          th Calculation Date
          th Base Amount
          th Target Currency
          th Wait Until
          th
          th

        tbody
          - @calculations.each do |calculation|
            tr
              td.fit = link_to 'View', calculation, class: 'btn btn-secondary'
              td = calculation.created_at.strftime("%-d %B, %Y")
              td = format_currency(calculation.base_amount, calculation.base_currency)
              td = calculation.target_currency
              td = calculation.wait_until.strftime("%-d %B, %Y")
              td.fit = link_to 'Edit', edit_calculation_path(calculation), class: 'btn btn-primary edit-btn'
              td.fit = link_to 'Delete', calculation_path(calculation), method: :delete, class: 'btn btn-danger delete-btn'

    - else
      h4.text-muted You have no calculations

app/views/calculations/new.slim
= form_for @calculation do |f|

  = @calculation.errors.full_messages

  .row
    .col
      .form-group
        = f.label :base_currency
        = f.select :base_currency, options_for_select(ExchangeRate::AVAILABLE_CURRENCIES), {}, class: 'form-control'

    .col
      .form-group
        = f.label :target_currency
        = f.select :target_currency, options_for_select(ExchangeRate::AVAILABLE_CURRENCIES), {}, class: 'form-control'

  .row
    .col
      .form-group
        = f.label :base_amount

        .input-group
          = f.text_field :base_amount, class: 'form-control'
          span.input-group-addon USD
    /.col
    /  .form-group
    /    = f.label :target_amount
    /
    /    .input-group
    /      = f.text_field :target_amount, disabled: true, class: 'form-control'
    /      span.input-group-addon USD

  .row

    .col
      .form-group
        = f.label :wait_until
        = f.text_field :wait_until, class: 'form-control'

    = f.submit 'Create Calculation', class: 'form-control'

app/views/calculations/show.slim
.row
  .col-sm-3
    .card
      .card-body
        h2.card-title #{@calculation.base_currency} → #{@calculation.target_currency}

        dl
          dt Amount
          dd = format_currency(@calculation.base_amount, @calculation.base_currency)

          dt Max Waiting Time
          dd = "#{(@calculation.created_at.to_date..@calculation.wait_until).count / 7} weeks"

          dt Created At
          dd = @calculation.created_at.strftime("%-d %B, %Y")

          dt Max Profit
          dd = format_currency(@top_profit_item[:profit], @calculation.target_currency)

          - if @top_profit_item[:profit] > 0
            dt Max Profit Week
            dd = "#{@top_profit_item[:week]} week"

          = link_to 'Edit', edit_calculation_path(@calculation)
  .col-sm-9

    ul.nav.nav-tabs role="tablist"
      li.nav-item
        a.nav-link.active data-toggle="tab" href="#forecast" Forecast chart
      li.nav-item
        a.nav-link data-toggle="tab" href="#history" Historical chart

    .tab-content
      .tab-pane.active id="forecast" role="tabpanel"
        #forecast-chart-container
      .tab-pane id="history" role="tabpanel"
        #historical-chart-container

- @chart_data.each do |value|
  input type="hidden" value="#{value[1][:weeks]}" id="#{value[0]}_weeks_array"
  input type="hidden" value="#{value[1][:amount]}" id="#{value[0]}_target_amount_array"

- if @top_profit_item[:profit] == 0
  .alert.alert-warning According to our information, you will not be able to receive any profit from this trade in the waiting time that you supplied.

table.table.table-bordered
  thead
    tr
      th Date
      th Exchange Rate
      th Amount
      th Profit
      th Rank
  tbody
    - @rate_data.each do |rate|
      tr
        td = "#{rate[:week]} week, #{rate[:year]}"
        td = "1 #{@calculation.base_currency} = #{format_currency(rate[:exchange_rate], @calculation.target_currency)}"
        td = format_currency(rate[:target_amount], @calculation.target_currency)
        td = format_currency(rate[:profit], @calculation.target_currency)
        td = rate[:rank]

= javascript_include_tag 'calculations_show'